# Lab6 - RNN


## Create data

Create 10 inputs and 10 outputs. Each input is one time-step, and contains a single feature. 

Each output value is 5 times the corresponding input value. 

In [1]:
X = list()
Y = list()
X = [x+1 for x in range(10)]
Y = [y * 5 for y in X]

print(X)
print(Y)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]


## Reshape Data
The input to the RNN layer should be in 3D shape i.e. (samples, time-steps, features).
- The samples are the number of samples in the input data. We have 10 samples in the input. 
- The time-steps is the number of time-steps per sample. We have 1 time-step. 
- Finally, features correspond to the number of features per time-step. We have one feature per time-step (univariate time series)

**model.add(SimpleRNN(50, activation='relu', input_shape=(n_steps, n_features)))**

In [2]:
import numpy as np

X = np.array(X).reshape(10, 1, 1)

In [3]:
X[0][0]

array([1])

## Create the model

The model has RNN layer with 50 neurons and relu activation functions. 
<br>The input shape is (1,1) since the data has one time-step with one feature. 

In [4]:
from keras.models import Sequential
from keras.layers import SimpleRNN, Dense

model = Sequential()
model.add(SimpleRNN(50, activation='relu', input_shape=(1, 1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
print(model.summary())

d:\Programs\Anaconda\envs\IA\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 50)             │         2,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            51 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,651 (10.36 KB)

 Trainable params: 2,651 (10.36 KB)

 Non-trainable params: 0 (0.00 B)

None


In [5]:
X = np.array(X)
Y = np.array(Y)
model.fit(X, Y, epochs=200, batch_size=1, validation_split=0.2, verbose = 0)

## Make predictions

Let's say we want to predict the output for an input of 30. The actual output should be 30 x 5 = 150. 

First, we need to convert our test data to the right shape i.e. 3D shape, as expected by RNN. 

In [8]:
test_input = np.array([30])
test_input = test_input.reshape((1, 1, 1))
test_output = model.predict(test_input, verbose=0)
print(test_output)

[[138.41127]]


# 2. One-to-One Sequence Problems with Multiple Features

In the previous example, each input sample had one time-step, where each time-step had one feature. 

In this example the input time-steps have multiple features - multivariate time-series.

## Create data

Create three lists: X1, X2, and Y. Each list has 25 elements, which means that that the total sample size is 25. Finally, Y contains the output.

In [9]:
nums = 25

X1 = list()
X2 = list()
X = list()
Y = list()

X1 = [(x+1)*2 for x in range(25)]
X2 = [(x+1)*3 for x in range(25)]
Y = [x1*x2 for x1,x2 in zip(X1,X2)]

print(X1)
print(X2)
print(Y)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]
[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75]
[6, 24, 54, 96, 150, 216, 294, 384, 486, 600, 726, 864, 1014, 1176, 1350, 1536, 1734, 1944, 2166, 2400, 2646, 2904, 3174, 3456, 3750]


The input will consist of the combination of X1 and X2 lists, where each list will be represented as a column. 

Here the X variable contains our final feature set. You can see it contains two columns i.e. two features per input

In [10]:
X = np.column_stack((X1, X2))
print(X)

[[ 2  3]
 [ 4  6]
 [ 6  9]
 [ 8 12]
 [10 15]
 [12 18]
 [14 21]
 [16 24]
 [18 27]
 [20 30]
 [22 33]
 [24 36]
 [26 39]
 [28 42]
 [30 45]
 [32 48]
 [34 51]
 [36 54]
 [38 57]
 [40 60]
 [42 63]
 [44 66]
 [46 69]
 [48 72]
 [50 75]]


## Reshape Data
The input to the RNN layer should be in 3D shape i.e. (samples, time-steps, features).
- The samples are the number of samples in the input data. We have 10 samples in the input. 
- The time-steps is the number of time-steps per sample. We have 1 time-step. 
- Finally, features correspond to the number of features per time-step. We have one feature per time-step (univariate time series)

**model.add(SimpleRNN(50, activation='relu', input_shape=(n_steps, n_features)))**

In [11]:
X = np.array(X).reshape(25, 1, 2)
print(X)

[[[ 2  3]]

 [[ 4  6]]

 [[ 6  9]]

 [[ 8 12]]

 [[10 15]]

 [[12 18]]

 [[14 21]]

 [[16 24]]

 [[18 27]]

 [[20 30]]

 [[22 33]]

 [[24 36]]

 [[26 39]]

 [[28 42]]

 [[30 45]]

 [[32 48]]

 [[34 51]]

 [[36 54]]

 [[38 57]]

 [[40 60]]

 [[42 63]]

 [[44 66]]

 [[46 69]]

 [[48 72]]

 [[50 75]]]


## Create the model

The RNN layer contains 80 neurons. We have two dense layers where first layer contains 10 neurons and the second dense layer, which also acts as the output layer, contains 1 neuron. 

In [12]:
model = Sequential()
model.add(SimpleRNN(80, activation='relu', input_shape=(1, 2)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
print(model.summary())

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)        │ (None, 80)             │         6,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            81 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 6,721 (26.25 KB)

 Trainable params: 6,721 (26.25 KB)

 Non-trainable params: 0 (0.00 B)

None


In [13]:
Y = np.array(Y).reshape((len(Y), 1))
model.fit(X, Y, epochs=200, batch_size=1, verbose = 0)

## Make predictions

The data point will have two features i.e. (55,80) the actual output should be 55 x 80 = 4400. Let's see what our algorithm predicts

In [13]:
test_input = np.array([55,80])
test_input = test_input.reshape((1, 1, 2))
test_output = model.predict(test_input, verbose=0)
print(test_output)

[[3099.9922]]


# 3. Many to One - Univariate (Single Feature)

Each input sample has more than one time-step, however the output consists of a single element. Each time-step in the input can have one or more features. 

We will start with many-to-one sequence problems having one feature, and then we will see how to solve many-to-one problems where input time-steps have multiple features.

## Data preparation

The following sequence is given: 

[10, 20, 30, 40, 50, 60, 70, 80, 90]

The goal is to divide the sequence into multiple input/output patterns called samples. 

Where N time steps are used as input and one time step is used as output.

If N = 3, then

      X ------  y

10, 20, 30 --- 40

20, 30, 40 --- 50

30, 40, 50 --- 60

## Data split function
The split_sequence() function implements the example above. It  will split a given univariate sequence into multiple samples where each sample has a specified number of time steps and the output is a single time step.

In [15]:
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

## Data preparation

In [16]:
import numpy as np

# define input sequence
seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(seq, n_steps)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


## Reshape Data

The model expects input shape for each sample in terms of the number of time steps and the number of features

**model.add(SimpleRNN(50, activation='relu', input_shape=(n_steps, n_features)))**

We are working with a univariate series, so the number of features is one, for one variable.

In [17]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

## Train the Vanilla RNN model

A Vanilla RNN is a model that has a single hidden layer of RNN units, and an output layer used to make a prediction.

In this case, we define a model with 10 RNN units in the hidden layer and an output layer that predicts a single numerical value.



In [18]:
# define model
model = Sequential()
model.add(SimpleRNN(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [19]:
# fit model
model.fit(X, y, epochs=200, verbose=0)

## Make a prediciton

In [20]:
# demonstrate prediction
x_input = np.array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
prediction = model.predict(x_input, verbose=0)
print(prediction)

[[108.21608]]


# HOMEWORK

Train a Many to One RNN networks.
Univariate time series, with 50 samples, and 4 time steps.

X = [5, 10, 15, 20, 25 ... 250] (before data preparation)

Y = [25, 30, 35, ... 250]

- **Tip**: create X, then use the data split function from above to create the new X and Y.
- Tip2: [(x+1)*5 for x in range(50)]

Use SimpleRNN layer with 100 units.

Train 2 models:
- 1st with activation function = RELU
- 2nd with activation function = tanh

Evaluate the models on test example:
- [1, 2, 3, 4]
- [300, 305, 310, 315]

In [22]:
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

In [23]:
# Create the data
X = [(x+1)*5 for x in range(50)]
Y = [(x+1)*5 + 20 for x in range(50)]

# Number of time steps
n_steps = 4

# Split the data into samples
X, Y = split_sequence(X, n_steps)

# Reshape the data to the required shape
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

print(X)
print(Y)

[[[  5]
  [ 10]
  [ 15]
  [ 20]]

 [[ 10]
  [ 15]
  [ 20]
  [ 25]]

 [[ 15]
  [ 20]
  [ 25]
  [ 30]]

 [[ 20]
  [ 25]
  [ 30]
  [ 35]]

 [[ 25]
  [ 30]
  [ 35]
  [ 40]]

 [[ 30]
  [ 35]
  [ 40]
  [ 45]]

 [[ 35]
  [ 40]
  [ 45]
  [ 50]]

 [[ 40]
  [ 45]
  [ 50]
  [ 55]]

 [[ 45]
  [ 50]
  [ 55]
  [ 60]]

 [[ 50]
  [ 55]
  [ 60]
  [ 65]]

 [[ 55]
  [ 60]
  [ 65]
  [ 70]]

 [[ 60]
  [ 65]
  [ 70]
  [ 75]]

 [[ 65]
  [ 70]
  [ 75]
  [ 80]]

 [[ 70]
  [ 75]
  [ 80]
  [ 85]]

 [[ 75]
  [ 80]
  [ 85]
  [ 90]]

 [[ 80]
  [ 85]
  [ 90]
  [ 95]]

 [[ 85]
  [ 90]
  [ 95]
  [100]]

 [[ 90]
  [ 95]
  [100]
  [105]]

 [[ 95]
  [100]
  [105]
  [110]]

 [[100]
  [105]
  [110]
  [115]]

 [[105]
  [110]
  [115]
  [120]]

 [[110]
  [115]
  [120]
  [125]]

 [[115]
  [120]
  [125]
  [130]]

 [[120]
  [125]
  [130]
  [135]]

 [[125]
  [130]
  [135]
  [140]]

 [[130]
  [135]
  [140]
  [145]]

 [[135]
  [140]
  [145]
  [150]]

 [[140]
  [145]
  [150]
  [155]]

 [[145]
  [150]
  [155]
  [160]]

 [[150]
  [155

In [26]:
# Define the first model with relu activation function
model_relu = Sequential()
model_relu.add(SimpleRNN(100, activation='relu', input_shape=(n_steps, n_features)))
model_relu.add(Dense(1))
model_relu.compile(optimizer='adam', loss='mse')
print(model_relu.summary())

d:\Programs\Anaconda\envs\IA\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_4 (SimpleRNN)        │ (None, 100)            │        10,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10,301 (40.24 KB)

 Trainable params: 10,301 (40.24 KB)

 Non-trainable params: 0 (0.00 B)

None


In [27]:
# Train the first model
model_relu.fit(X, Y, epochs=200, verbose=0)

In [33]:
# Test example 1
test_input_relu = np.array([1, 2, 3, 4])
test_input_relu = test_input_relu.reshape((1, n_steps, n_features))
prediction_relu = model_relu.predict(test_input_relu, verbose=0)
print(f"Prediction for [1, 2, 3, 4]: {prediction_relu}")

Prediction for [1, 2, 3, 4]: [[4.15465]]


In [34]:
# Test example 2
test_input_relu2 = np.array([300, 305, 310, 315])
test_input_relu2 = test_input_relu2.reshape((1, n_steps, n_features))
prediction_relu2 = model_relu.predict(test_input_relu2, verbose=0)
print(f"Prediction for [300, 305, 310, 315]: {prediction_relu2}")

Prediction for [300, 305, 310, 315]: [[327.4006]]


In [35]:
# Define the second model with tanh activation function
model_tanh = Sequential()
model_tanh.add(SimpleRNN(100, activation='tanh', input_shape=(n_steps, n_features)))
model_tanh.add(Dense(1))
model_tanh.compile(optimizer='adam', loss='mse')
print(model_tanh.summary())

d:\Programs\Anaconda\envs\IA\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_5 (SimpleRNN)        │ (None, 100)            │        10,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10,301 (40.24 KB)

 Trainable params: 10,301 (40.24 KB)

 Non-trainable params: 0 (0.00 B)

None


In [36]:
# Train the second model
model_tanh.fit(X, Y, epochs=200, verbose=0)

In [37]:
# Test example 1
test_input_tanh = np.array([1, 2, 3, 4])
test_input_tanh = test_input_tanh.reshape((1, n_steps, n_features))
prediction_tanh = model_tanh.predict(test_input_tanh, verbose=0)
print(f"Prediction for [1, 2, 3, 4]: {prediction_tanh}")

Prediction for [1, 2, 3, 4]: [[13.895441]]


In [38]:
# Test example 2
test_input_tanh2 = np.array([300, 305, 310, 315])
test_input_tanh2 = test_input_tanh2.reshape((1, n_steps, n_features))
prediction_tanh2 = model_tanh.predict(test_input_tanh2, verbose=0)
print(f"Prediction for [300, 305, 310, 315]: {prediction_tanh2}")

Prediction for [300, 305, 310, 315]: [[42.63798]]
